name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Jalankan setiap hari pada tengah malam
  push:
    branches:
      - main
  workflow_dispatch: # Memungkinkan menjalankan manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anmol098/waka-readme-stats@v2.17
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update README with new stats"
          git push
